[package]
name = "arborist"
version = "0.1.0"
authors = ["Matt Garnett <matt.garnett@me.com>"]
edition = "2018"

[dependencies]
arrayref = "0.3.5"
bonsai = { path = "../bonsai", default-features = false, features=["u128"] }
sha2 = "0.8.0"

[dev-dependencies]
pretty_assertions = "0.6.1"

